
### IJPL-205919 public exponent is in int
< {%

    let algorithm = {
        name: 'RSASSA-PKCS1-v1_5',
        modulusLength: 4096,                       // 2048 or 4096 bits recommended
        publicExponent:  65537, // (standard exponent)
        hash: "SHA-512"
    };
    const pair = crypto.subtle.generateKey(algorithm,
        true,
        ['sign', 'verify']);

    let otherClaim = 'Servus, HTTP Client Pre Script!!!';

    const rsaSignature = crypto.subtle.sign({
            name: "RSASSA-PKCS1-v1_5",
            saltLength: 32,
        },
        pair.privateKey,
        Uint8Array.from(otherClaim, c => c.charCodeAt(0)))

    console.log(`verify ${otherClaim}: ${crypto.subtle.verify({
        name: "RSASSA-PKCS1-v1_5",
        saltLength: 32,
    }, pair.publicKey, rsaSignature, Uint8Array.from(otherClaim, c => c.charCodeAt(0)))}`);

%}

GET examples.http-client.intellij.net/anything